-- phpMyAdmin SQL Dump
-- version 4.8.0.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Aug 17, 2020 at 11:04 AM
-- Server version: 10.1.32-MariaDB
-- PHP Version: 5.6.36

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `aaotravel`
--

-- --------------------------------------------------------

--
-- Table structure for table `package_detail_itinerary`
--

CREATE TABLE `package_detail_itinerary` (
  `ID` int(5) NOT NULL,
  `Package_ID` int(3) NOT NULL,
  `day` varchar(5) NOT NULL,
  `content` mediumtext NOT NULL,
  `route` varchar(500) NOT NULL,
  `map` varchar(5000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `package_detail_itinerary`
--

INSERT INTO `package_detail_itinerary` (`ID`, `Package_ID`, `day`, `content`, `route`, `map`) VALUES
(3001, 301, '1', '<h5 style=\"font-weight:bolder\">Delhi to Agra</h5> \r\n<p style=\"text-align: justify;\">This morning, embark on a leisurely drive to Agra, city of the world famous Taj Mahal. En-route make a brief stop at Sikandra, the tomb of great Mughal emperor Akbar.</p> <p style=\"text-align: justify;\"> Upon arrival in Agra, check in at your hotel and enjoy an evening at leisure in Agra. </p>', ' Route : Delhi <i class=\"fas fa-long-arrow-alt-right\"></i> Agra <i class=\"fas fa-long-arrow-alt-right\"></i> Delhi ', '<p style=\"font-weight:bolder; margin-top:20px;\">Route Map :</p><iframe src=\"https://www.google.com/maps/embed?pb=!1m34!1m12!1m3!1d1804798.0347275673!2d76.49058533587036!3d27.932762923177595!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!4m19!3e0!4m5!1s0x390cfd5b347eb62d%3A0x37205b715389640!2sDelhi%2C+India!3m2!1d28.7040592!2d77.10249019999999!4m5!1s0x39740d857c2f41d9%3A0x784aef38a9523b42!2sAgra%2C+Uttar+Pradesh%2C+India!3m2!1d27.1766701!2d78.00807449999999!4m5!1s0x390cfd5b347eb62d%3A0x37205b715389640!2sDelhi%2C+India!3m2!1d28.7040592!2d77.10249019999999!5e0!3m2!1sen!2sus!4v1543747695284\" width=\"100%\" height=\"400\" frameborder=\"0\" style=\"border:0\" allowfullscreen></iframe>'),
(3002, 301, '2', '<h5 style=\"font-weight:bolder\">Day in Agra</h5> \r\n<p style=\"text-align: justify;\">This morning, experience the awe-inspiring beauty of the eternal symbol of love, the Taj Mahal. Often referred to as a poem in white marble, Taj Mahal displays the saga of love between Emperor Shah Jahan and Mumtaz Mahal. Also visit the Agra fort, which is built in red sandstone and has magnificent palaces, halls of public and private audience and beautiful gardens.</p> <p style=\"text-align: justify;\">Later, visit marble inlay workshops and indulge in exquisite shopping in the culture and tradition filled city of Agra. This evening, you have the option to watch a fantastic show \"Mohabbat the Taj - The saga of love\", staging the largest replica of the Taj Mahal, and presenting the Taj in its various shades and seasons.</p>', '', ''),
(3003, 301, '3', '</h5 style=\"font-weight:bolder\">Agra to Delhi </h5>\r\n<p style=\"text-align: justify;\">After breakfast, drive back to Delhi, where you will be transferred to your hotel.</p>', '', ''),
(3004, 302, '1', '<h5 style=\"font-weight:bolder\">Arrive Goa, the beach heaven of India</h5>\r\n\r\n\r\n\r\n<p style=\"text-align: justify;\">Arrive in India, for your Beach Paradise - Goa Tour.</p>\r\n\r\n\r\n\r\n<h5 style=\"font-weight:bolder;\">PM :</h5>	\r\n\r\n\r\n\r\n<ul>\r\n\r\n\r\n\r\n<li class=\"\"> Arrive Goa </li>\r\n\r\n\r\n\r\n<li class=\"\"> Welcome to Goa </li> \r\n\r\n<li class=\"\"> Transfer To hotel </li>\r\n\r\n</ul>', ' Route : Goa', '<p style=\"font-weight:bolder; margin-top:20px;\">Route Map :</p><iframe src=\"https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3940783.3534643753!2d74.123996!3d15.299325999999999!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bbfba106336b741%3A0xeaf887ff62f34092!2sGoa%2C+India!5e0!3m2!1sen!2sus!4v1543861478734\" width=\"100%\" height=\"400\" frameborder=\"0\" style=\"border:0\" allowfullscreen></iframe>'),
(3005, 302, '2', '<h5 style=\"font-weight:bolder;\">Discover Goa</h5>\r\n<p style=\"text-algin:justify\">Discover the people and heritage of Goa, on your Beach Paradise - Goa Tour.</p>\r\n<h5 style=\"font-weight:bolder;\">AM :</h5>	\r\n<ul class=\"\">\r\n<li class=\"\" style=\"text-align:justify; \">Take a half day tour of new and old Goa seeing the typical Portuguese Goan architecture and the Basilica of Bom Jesus, where the remains of St Francis Xavier lie in a dazzling silver casket.\r\n</li>\r\n</ul>\r\n<h5 style=\"font-weight:bolder;\">PM :</h5>	\r\n<ul class=\"\">\r\n<li class=\"\" style=\"text-align:justify; \">In the evening, take a boat cruise on the river Mandovi, a pleasant way to spend a thoroughly enjoyable evening in Goa.  \r\n</li> </ul>', '', ''),
(3006, 302, '3,4,5', '<h5 style=\"font-weight:bolder;\">Relax by the sunny beaches of Goa</h5>\r\nRelax and rejuvenate in Goa, on your Beach Paradise - Goa Tour.\r\n<h5 style=\"font-weight:bolder;\">AM & PM :</h5>\r\n<ul class=\"\">\r\n<li class=\"\" style=\"text-align:justify; \">Enjoy your time at leisure to relax on the beach or pamper yourself with the various facilities offered by your hotel.\r\n</li>\r\n<li class=\"\" style=\"text-align:justify; \"> The Goan food and Fenny (a speciality Goan liquor made from coconut) along with the lovely Goan people and warm coastal climate will pamper you to the max! \r\n</li>\r\n</ul>', '', ''),
(3007, 302, '6', '<h5 style=\"font-weight:bolder;\">DEPARTURE</h5>\r\n\r\nBig goodbye to Goa, as you reach the finale of your Beach Paradise - Goa Tour.\r\n\r\n<h5 style=\"font-weight:bolder\">AM :</h5>\r\n\r\n<ul class=\"\">\r\n\r\n<li class=\"\" style=\"text-align:justify; \">This morning, you will be transferred to Goa airport to catch your flight for onward destination\r\n\r\n</li>\r\n\r\n</ul>', '', ''),
(3008, 303, '1', '<h5 style=\"font-weight:bolder;\"> Drive Kochi to Alleppey; Cruise Alleppey to Kumarakom</h5>\r\n<p style=\"text-algin:justify\">This morning, embark on a leisurely drive to Alleppey. Upon arrival at Alleppey jetty, board\r\nyour houseboat to cruise through the backwaters. Kerala backwaters consist of a complex\r\nnetwork of lagoons, lakes, & canals and are best experienced while slowly rowing down the\r\nlabyrinth of canals in a traditional thatch-roofed houseboat, known as \'Kettuvallam\'. See life\r\non the banks, lush green rice fields, and coconut groves with occasional temple or church as\r\nyou cruise through the canals. Enjoy the special Kerala style meals prepared by your chef on\r\nboard. Overnight stay at houseboat.</p>', ' Route : Kochi <i class=\"fas fa-long-arrow-alt-right\"></i> Alleppey <i class=\"fas fa-long-arrow-alt-right\"></i> Kumarakom <i class=\"fas fa-long-arrow-alt-right\"></i> Kochi ', '<p style=\"font-weight:bolder; margin-top:20px;\">Route Map :</p><iframe src=\"https://www.google.com/maps/embed?pb=!1m40!1m12!1m3!1d251686.92174157736!2d76.20940442666397!3d9.714445117230436!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!4m25!3e0!4m5!1s0x3b080d514abec6bf%3A0xbd582caa5844192!2sKochi%2C+Kerala%2C+India!3m2!1d9.9312328!2d76.26730409999999!4m5!1s0x3b0884f1aa296b61%3A0xb84764552c41f85a!2sAlappuzha%2C+Kerala%2C+India!3m2!1d9.498066699999999!2d76.3388484!4m5!1s0x3b0881caaef0a8f7%3A0xc23075c3529e921!2sKumarakom%2C+Kerala%2C+India!3m2!1d9.6175449!2d76.430095!4m5!1s0x3b080d514abec6bf%3A0xbd582caa5844192!2sKochi%2C+Kerala%2C+India!3m2!1d9.9312328!2d76.26730409999999!5e0!3m2!1sen!2sus!4v1543861752498\" width=\"100%\" height=\"400\" frameborder=\"0\" style=\"border:0\" allowfullscreen></iframe>'),
(3009, 303, '2', '<h5 style=\"font-weight:bolder;\">Day in Kumarakom</h5>\r\n\r\n\r\n\r\n<p style=\"text-algin:justify\">This morning, enjoy breakfast on board. Alight your houseboat at Kumarakom. Visit the\r\n\r\n\r\n\r\nKumarakom bird sanctuary on the banks of Vembanad Lake. This sanctuary is spread over 100\r\n\r\n\r\n\r\nacres and is home to thousands of resident and migratory birds. Some commonly found\r\n\r\n\r\n\r\nspecies include egret, darter, waterfowl, heron, bittern, kites, marsh harries, kingfishers,\r\n\r\n\r\n\r\nwoodpeckers and wild ducks.\r\n\r\n\r\n\r\nEnjoy an evening at leisure in Kumarakom.</p>', '', ''),
(3010, 303, '3', '<h5 style=\"font-weight:bolder;\">Kumarakom to Kochi</h5>\r\n\r\n<p style=\"text-algin:justify\">After breakfast, drive back to Kochi, where you will be transferred to your hotel.</p>', '', ''),
(3011, 304, '1', '<h5 style=\"font-weight:bolder;\">Delhi to Amritsar</h5>\r\n\r\n<p style=\"text-algin:justify\">Early this morning, catch your express train to Amrtisar, city of the Golden Temple.\r\n\r\nAfter lunch, relax at hotel. Later in the afternoon, proceed to the India - Pakistan border. You\r\n\r\nwill visit the Wagah Border, to see the \'lowering of the flags\' ceremony. This unique ceremony\r\n\r\ninvolves a parade by Indian Border Security Force and Pakistan Rangers soldiers.</p>', ' Delhi <i class=\"fas fa-long-arrow-alt-right\"></i>  Amritsar <i class=\"fas fa-long-arrow-alt-right\"></i>  Delhi ', '<p style=\"font-weight:bolder; margin-top:20px;\"><iframe src=\"https://www.google.com/maps/embed?pb=!1m34!1m12!1m3!1d1766249.1557639702!2d74.89417702672966!3d30.15983813463339!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!4m19!3e0!4m5!1s0x390cfd5b347eb62d%3A0x37205b715389640!2sDelhi%2C+India!3m2!1d28.7040592!2d77.10249019999999!4m5!1s0x391964aa569e7355%3A0xeea2605bee84ef7d!2sAmritsar%2C+Punjab%2C+India!3m2!1d31.6339793!2d74.8722642!4m5!1s0x390cfd5b347eb62d%3A0x37205b715389640!2sDelhi%2C+India!3m2!1d28.7040592!2d77.10249019999999!5e0!3m2!1sen!2sus!4v1543862042699\" width=\"100%\" height=\"400\" frameborder=\"0\" style=\"border:0\" allowfullscreen></iframe>'),
(3012, 304, '2', '<h5 style=\"font-weight:bolder;\">Day in Amritsar</h5>\r\n\r\n\r\n\r\n<p style=\"text-algin:justify\">After breakfast take a city tour of Amritsar visiting the Golden Temple (the most popular Sikh\r\n\r\n\r\n\r\ntemple in India), Jallianwallah Bagh (famous gardens close to the Golden Temple, which\r\n\r\n\r\n\r\nnarrate the story of the most horrific pre-independence massacre in India), Durgiana Temple\r\n\r\n\r\n\r\n(the largest Hindu temple in Amritsar) and the Ram Bagh museum.</p>\r\n\r\n\r\n<p style=\"text-algin:justify\">\r\nLater in the afternoon, stroll through the local bazaars of Amritsar getting a glimpse of local\r\n\r\n\r\n\r\nlifestyle in this holy city.</p>', '', ''),
(3013, 304, '3', '<h5 style=\"font-weight:bolder;\">Amritsar to Delhi</h5>\r\n<p style=\"text-algin:justify\">Today, catch your return train to Delhi, where you will be transferred to your hotel.</p>', '', ''),
(3014, 305, '1', '<h5 style=\"font-weight:bolder;\">Delhi to Mandawa</h5>\r\n\r\n<p style=\"text-algin:justify\">This morning, drive to Mandawa, a quaint village in the heart of Shekhawati region. Mandawa\r\n\r\nhas some of the finest frescos and painted havelis in the region, and is a perfect place to\r\n\r\nappreciate the art of bygone era. Spend the afternoon discovering Mandawa and visiting the\r\n\r\nunique havelis of the region.</p>', ' Delhi <i class=\"fas fa-long-arrow-alt-right\"></i> Mandawa <i class=\"fas fa-long-arrow-alt-right\"></i> Pushkar <i class=\"fas fa-long-arrow-alt-right\"></i> Jaipur <i class=\"fas fa-long-arrow-alt-right\"></i> Delhi ', '<p style=\"font-weight:bolder; margin-top:20px;\">Route Map :</p><iframe src=\"https://www.google.com/maps/embed?pb=!1m46!1m12!1m3!1d1809076.0161596925!2d74.71456027281374!3d27.675526103650206!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!4m31!3e0!4m5!1s0x390cfd5b347eb62d%3A0x37205b715389640!2sDelhi%2C+India!3m2!1d28.7040592!2d77.10249019999999!4m5!1s0x39135ab1dc006611%3A0x3acebe2639825020!2sMandawa%2C+Rajasthan+333704%2C+India!3m2!1d28.050017!2d75.14870069999999!4m5!1s0x396bdd22e5572a2f%3A0xb8733d912fcdf2ea!2sPushkar%2C+Rajasthan%2C+India!3m2!1d26.489749!2d74.5510856!4m5!1s0x396c4adf4c57e281%3A0xce1c63a0cf22e09!2sJaipur%2C+Rajasthan%2C+India!3m2!1d26.9124336!2d75.7872709!4m5!1s0x390cfd5b347eb62d%3A0x37205b715389640!2sDelhi%2C+India!3m2!1d28.7040592!2d77.10249019999999!5e0!3m2!1sen!2sus!4v1543861672469\" width=\"100%\" height=\"400\" frameborder=\"0\" style=\"border:0\" allowfullscreen></iframe><p style=\"font-weight:bolder; margin-top:20px;\">Route Map :</p>'),
(3015, 305, '2', '<h5 style=\"font-weight:bolder;\">Mandawa to Pushkar</h5>\r\n\r\n\r\n\r\n<p style=\"text-algin:justify\">After breakfast, embark on a drive amidst the arid Rajasthan desert towards Pushkar, a land of\r\n\r\n\r\n\r\nfairs in the heart of Rajasthan. Famous for the annual cattle and camel fair in November,\r\n\r\n\r\n\r\nPushkar is also one of the holiest cities of India, being one of the 5 sacred dhams (pilgrimage\r\n\r\n\r\n\r\nsite) for Hindu devotees.</p>\r\n\r\n\r\n<p style=\"text-algin:justify\">\r\nThis afternoon, enjoy a sightseeing tour of Pushkar, mingling with saadhu\'s (holy men in their\r\n\r\n\r\n\r\norange attires), visiting the holy Pushkar Lake and the various temples in the region. The most\r\n\r\n\r\n\r\nfamous is the Brahma Temple, said to be the only temple in the world dedicated to Lord\r\n\r\n\r\n\r\nBrahma. Later, enjoy an evening sunset camel safari, followed by dinner with Rajasthani\r\n\r\n\r\n\r\ncultural performance.</p>', '', ''),
(3016, 305, '3', '<h5 style=\"font-weight:bolder;\">Pushkar to Jaipur</h5>\r\n\r\n<p style=\"text-algin:justify\">This morning, drive to Jaipur - land of the Rajputs. Jaipur is an exuberance of colour, dance and\r\n\r\ntraditional arts and crafts. Known, as the \'Pink City\', Jaipur is home to ancient forts and palaces\r\n\r\nand is one of India\'s most well planned cities.</p>\r\n<p style=\"text-algin:justify\">\r\nThis afternoon, visit the City Palace complex with its museums and Jantar Mantar, the ancient\r\n\r\nastronomical observatory. Also drive past Hawa Mahal (Palace of Winds), built in the 18th\r\n\r\ncentury. This palace with its innumerable windows and screened balconies was especially\r\n\r\nbuilt for the royal women to view the city and processions from behind their purdahs.</p>\r\n\r\n', '', ''),
(3017, 305, '4', '<h5 style=\"font-weight:bolder;\">Day in Jaipur</h5>\r\n\r\n<p style=\"text-algin:justify\">After breakfast, visit the Amber fort, which was built in the 16th century. An elephant ride will\r\n\r\nhelp you ascend to this hilltop fort (elephants are subject to availability). Alternatively, you\r\n\r\ncould choose to walk or drive up to the fort.</p>\r\n<p style=\"text-algin:justify\">\r\nThen, enjoy a short excursion to Sanganer village, renowned for its local crafts such as block\r\n\r\nprinted textiles and hand made paper. Sanganer block printing technique uses wooden blocks\r\n\r\nwith carved designs to make colourful motif\'s on fabrics. You will get the opportunity to see\r\n\r\nthe traditional printing and paper making process first hand and even interact with local\r\n\r\nartisans and villagers.</p>\r\n<p style=\"text-algin:justify\">\r\nThe \'Pink City\', of Jaipur is well known for its beautiful carpets, enamelled ornaments, precious\r\n\r\nand semi-precious stones, brassware and many other arts and crafts. Later in the afternoon,\r\n\r\nvisit gem and carpet weaving factories, and enjoy haggling for souvenirs in colourful bazaars\r\n\r\nof Jaipur.</p>', '', ''),
(3018, 305, '5', '<h5 style=\"font-weight:bolder;\">Jaipur to Delhi</h5>\r\nAfter breakfast, drive back to Delhi, where you will be transferred to your hotel.', '', ''),
(3019, 306, '1', '<h5 style=\"font-weight:bolder;\">Arrive Mumbai</h5>\r\n\r\n<p style=\"text-algin:justify\">Upon your arrival at Mumbai airport, you will be met by our representative and escorted to\r\n\r\nyour hotel.</p>', 'Visit Mumbai, home to Bollywood and India’s financial and celluloid capital ', ''),
(3020, 306, '2', '<h5 style=\"font-weight:bolder;\">Day in Mumbai</h5>\r\n\r\n\r\n\r\n<p style=\"text-algin:justify\">After breakfast, embark for an excursion tour to the rock cut Elephanta Caves (located 10 Km\r\n\r\n\r\n\r\nfrom the Gateway of India, Mumbai). A short ferry ride takes you across the harbour to the\r\n\r\n\r\n\r\nisland of Elephanta for a visit to the Great Cave Temple, which dates back to 550 A.D.\r\n\r\n\r\n\r\nElephanta\'s most striking figure represents the three aspects of Shiva - the creator, preserver\r\n\r\n\r\n\r\nand destroyer.</p>\r\n\r\n<p style=\"text-algin:justify\">\r\n\r\nThis afternoon, enjoy a city tour of Mumbai visiting the Prince of Wales Museum, Gateway of\r\n\r\n\r\n\r\nIndia, Gandhi museum and the bustling Dhobi Ghats, where you will see hundreds of men and\r\n\r\n\r\n\r\ntheir families engaged in the family business of washing clothes.</p>', '', ''),
(3021, 306, '3', '<h5 style=\"font-weight:bolder;\">Depart Mumbai</h5>\r\n\r\n<p style=\"text-algin:justify\">After breakfast, proceed to the airport to board your flight for onward destination.</p>', '', ''),
(3022, 307, '1', '<h5 style=\"font-weight:bolder;\">Arrive Chennai</h5>\r\n\r\n<p style=\"text-algin:justify\">Upon your arrival at Chennai airport, you will be met by our representative and escorted to\r\n\r\nyour hotel for 2 nights stay.</p>', 'Visit the eastern coastal bliss, Chennai, the city that grew from a fishemen’s village', ''),
(3023, 307, '2', '<h5 style=\"font-weight:bolder;\">Day in Chennai</h5>\r\n\r\n<p style=\"text-algin:justify\">Today, enjoy a city tour of Chennai, driving along the Marina Beach (which stretches for over\r\n\r\n12 km); visiting St Mary\'s Church (India\'s oldest surviving British church built in 1680) and Fort\r\n\r\nSt George (built by the British around 1653). Also visit the National Art Gallery and Santhome\r\n\r\nCathedral.</p>', '', ''),
(3024, 307, '3', '<h5 style=\"font-weight:bolder;\">Depart Chennai</h5>\r\n\r\n<p style=\"text-algin:justify\">After breakfast proceed to the airport to board your flight for onward journey</p>', '', ''),
(3025, 308, '1', '<h5 style=\"font-weight:bolder;\">Arrive Kolkata</h5>\r\n\r\n<p style=\"text-algin:justify\">Upon your arrival at Kolkata airport, you will be met by our representative and escorted to\r\n\r\nyour hotel for 2 nights stay.</p>\r\n\r\n', 'Discover Kolkata, the east Indian city of Joy, famous as the culture capital of India. ', ''),
(3026, 308, '2', '<h5 style=\"font-weight:bolder;\">Day in Kolkata</h5>\r\n\r\n<p style=\"text-algin:justify\">Enjoy a sightseeing tour of Kolkata, visiting Victoria Memorial, a white marble structure built to commemorate the memory of Queen Victoria of England; the Kali temple, an ancient temple dedicated to goddess Kali, from which the city of Kolkata derives its name; the famous Jain Temple; drive past Fort William, a colonial fort built by the British to guard the city against the French; and the Secretariat, a remnant of colonial architecture in the city.</p><p style=\"text-algin:justify\">\r\nAlso visit the local markets in Kolkata where you can see artisans making idols of Hindu gods,\r\nand doing gorgeous embroidery work on Indian attires. Kolkata is famous for its traditional\r\nsweets, Bengali Sarees, Murshidabad silks, and authentic handicrafts.</p>\r\n\r\n', '', ''),
(3027, 308, '3', '<h5 style=\"font-weight:bolder;\">Depart Kolkata</h5>\r\n<p style=\"text-algin:justify\">After breakfast proceed to the airport to board your flight for onward destination.</p>', '', ''),
(3028, 309, '1', '<h5 style=\"font-weight:bolder;\">Arrive Varanasi</h5>\r\n\r\n<p style=\"text-algin:justify\">Upon your arrival at Varanasi airport, you will be met by our representative and escorted to your hotel.</p>\r\n<p style=\"text-algin:justify\">\r\nVaranasi is the spiritual capital of India (also known as Kashi and Benaras). Enjoy an afternoon\r\nat leisure at your hotel or explore the streets of Varanasi on your own.</p>\r\n<p style=\"text-algin:justify\">\r\nThis evening, take a rikshaw ride to the ghats to see the grand \'Aarti\' ceremony conducted\r\n\r\neveryday at sunset by white-robed priests. The young priests sway in seemingly\r\n\r\nchoreographed movements, worshiping the river goddess with incense, flowers and earthen\r\n\r\nlamps - a spectacular and unique sight.\r\n\r\n', 'Explore Varanasi, the oldest living city in the world and the spiritual hub of India', ''),
(3029, 309, '2', '<h5 style=\"font-weight:bolder;\">Day in Varanasi</h5>\r\n\r\n<p style=\"text-algin:justify\">This morning, enjoy a boat cruise at dawn on the Holy River Ganges in Varanasi. See the \'bathing ghats\' where thousands of pilgrims pay homage to the Sun God by immersing themselves in the holy water of River Ganges, and the \'burning ghats\' where cremations are conducted.\r\n<p style=\"text-algin:justify\">\r\nIn the afternoon, visit Sarnath, the place where Lord Buddha gave his first sermon. Sarnath\r\nwas a renowned school of learning from 6th century BC to 12th century AD. The Ashoka pillar\r\nof Sarnath is the national emblem of India. Visit the ruins, stupa, Buddhist temple and the\r\nSarnath Museum.</p>\r\n\r\n', '', ''),
(3030, 309, '3', '<h5 style=\"font-weight:bolder;\">Depart Varanasi</h5>\r\n\r\n<p style=\"text-algin:justify\">After breakfast, proceed to the airport to board your flight for onward destination.</p>', '', '');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `package_detail_itinerary`
--
ALTER TABLE `package_detail_itinerary`
  ADD PRIMARY KEY (`ID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `package_detail_itinerary`
--
ALTER TABLE `package_detail_itinerary`
  MODIFY `ID` int(5) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3031;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
