-- phpMyAdmin SQL Dump
-- version 4.8.0.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Nov 25, 2018 at 04:06 PM
-- Server version: 10.1.32-MariaDB
-- PHP Version: 5.6.36

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `travels`
--

-- --------------------------------------------------------

--
-- Table structure for table `hotels`
--

CREATE TABLE `hotels` (
  `h_id` int(10) NOT NULL,
  `Name` varchar(30) NOT NULL,
  `Type_ID` int(2) NOT NULL,
  `Amount` varchar(20) NOT NULL,
  `Description` mediumtext NOT NULL,
  `Address` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `hotels`
--

INSERT INTO `hotels` (`h_id`, `Name`, `Type_ID`, `Amount`, `Description`, `Address`) VALUES
(201, 'RAJ MAHAL HOTEL ', 3, 'Rs.5000', '<h2>Raj Mahal Hotel</h2>\r\n<p style=\"text-align:justify;\">RAJMAHAL HOTEL, AGRA invites you to bask in an atmosphere which is a blend of contemporary ambience and hospitality at its warmest. It is nestled at stone\'s throw distance from the world\'s awesome wonder – The Taj Mahal. You just have to draw the curtain of your window and there it is looming large on the horizon.</p>\r\n<p style=\"text-align:justify;\">Starlit sparkling lobby and smiling team of the Hotel extends the traditional Indian welcome to your most solicited presence with its open arms, marigold and rose garlands and an auspicious red \"tilak\" on your forehead.</p>\r\n<p style=\"text-align:justify;\">Soothing aesthetics at the forefront, cozy rooms with modern furnishings, instantly embraces your thought - \"home away from home\", an honest effort to ensure every comfort while you are with us.</p>\r\n<p style=\"text-align:justify;\">Zaika - our world dining restaurant caters to one and all taste buds. The sumptuous variety of culinary is served on your plate from our hygienic and modern kitchen prepared by seasoned commissars.</p>\r\n', ' 1/2, Taj Nagri Phase-II, Fatehabad Road, Agra, 282 001 (Uttar Pradesh), India\r\n'),
(202, 'MANSINGH PALACE HOTEL', 2, 'Rs.4000', '<h2>Mansingh Palace</h2>\r\n<p style=\"text-align:justify;\">Located in the heart of Agra, this hotel is 4 km from the railway station and 6 km from the airport.\r\nBearing a total of 100 rooms, this place boasts Sheesh Mahal, the multi-cuisine restaurant. There is\r\nalso Ripples, the coffee shop, which is a great place to relax, or they can simply unwind at The Tequila,\r\nthe bar, which serves the choicest variety of liquors. Business travelers are also provided with a\r\nconference hall to conduct formal meetings.</p>\r\n\r\n			  <p style=\"text-align:justify;\">The gourmets can satiate their taste buds at Sheesh Mahal, the multi-cuisine restaurant that serves\r\nsome delectable dishes. They can relax at the Ripples, the coffee shop, or simply unwind at The\r\nTequila, the bar, which serves the choicest variety of liquors. The business travelers can also avail of\r\nthe conference hall to conduct formal meetings.</p>\r\n', 'Fatehabad road, Agra - 282001 '),
(203, 'MARQUIS BEACH RESORT', 1, 'Rs.3000', '<h2>Marquis Beach Resort</h2>\r\n<p style=\"text-align:justify\">Marquis Beach Resort is geographically located in Candolim, Goa bang on a beautiful stretch of beach. The Candolim beach on the resort front is famous for adventurous water sports activity, with the lighthouse, shopping area, flea & Saturday markets located in close proximity.</p><p style=\"text-align:justify\"> The resort is designed with class and elegant style. Each and every detail is just perfect and offers the visitors luxury, one can only dream of - unpolluted atmosphere, crystal clean water, absolute calm and privacy, acres of gardens and a beautiful stretch of golden sands. </p>', 'near kingfisher villa, Dando - Candolim'),
(204, 'LEMON TREE AMARANTE RESORT', 3, 'Rs.5500', '<h2>Lemon Tree Amanrante Resort</h2>\r\n<p style=\"text-align:justify\">Unwind at this upscale, full-service moderately priced resort. Ideal for both leisure and business travelers, the Lemon Tree Amarante Beach Resort has been designed to evoke the poetry, history and romance of 15th century Portugal. It creates an ambience which is visually stunning - with medieval oil paintings, artifacts, tile work, heraldry and stained glass set amidst a lush green environment and calm water bodies. The resort features stylish guest rooms and suites, warm and personalized service and a full range of amenities. Candolim Beach is a mere 250 meters from the hotel while curio shops, local attractions and entertainment options are all available nearby. It offers 65 guest rooms and suites, all designed for rest and relaxation. Large window spaces with cozy seats, add to the old world charm of the resort. </p>', 'Vadi, Candolim Bardez,\r\n'),
(205, 'CASINO HOTEL ', 3, 'Rs.4500', '<h2>Casino Hotel </h2>\r\n	<p style=\"text-align:justify\">C	asino Hotel is one of the well-known upmarket hotels of Kochi. The hotel is located on Willingdon Island, which is a short drive away from Cochin International Airport. The Hotel offers a perfect blend of traditional hospitality and modern day luxurious comforts. With a focus on Keralan architecture, bamboo and woodwork, the hotels beautiful natural surroundings provide a perfect setting for a stress free holiday. Casino hotel offers 67 centrally air conditioned rooms, equipped with all modern facilities. </p>', ' Casino Building, Willingdon Island, Kochi, Kerala 682003\r\n'),
(206, 'FORT HERITAGE ', 1, 'Rs.3500', '<h2>Fort Heritage </h2>\r\n	<p style=\"text-align:justify\">This establishment is situated near Fort Cochin and its popular beach. Other attractions within close proximity to the Fort Heritage include the Chinese Fishing Nets and the historic Church of St. Francis. The city center is the site of most of the commercial attractions. From the Fort Heritage, the nearest international airport is located in Nedumbassery, approximately 13 miles from the city center.</p><p style=\"text-align:justify\"> The rooms at the Fort Heritage are provided with conveniences which include direct-dial telephone service and cable television service. Hot water is available around the clock. The private baths are equipped with both tubs and showers.</p><p style=\"text-align:justify\"> Guests of the Fort Heritage will be provided with access to a host of Ayurvedic treatments right on the premises. The hotel offers massages and other relaxing options. There is a restaurant located at the hotel whose offerings include Syrian, Continental and local dishes. Guests may also take advantage of the hotels gardens where they can enjoy their breakfast.</p> ', ' 1/283, Napier Street, Elphinstone Road, Fort Cochin Kochi, Kerala 682001'),
(207, 'GOLDEN TULIP  HOTEL', 2, 'Rs.4500', '<h2>Golden Tulip  Hotel</h2>\r\n	<p style=\"text-align:justify\">Golden Tulip Hospitality Group, with its head office in France, is a worldwide hospitality company with more than 1000 hotels and 76,000 rooms in 50 countries. The Golden Tulip Hospitality Group franchises and manages hotels in Europe, Middle East & Africa, Asian Pacific Region and America with brands like Golden Tulip, Tulip Inn and Royal Tulip.</p> <p style=\"text-align:justify\"> with its head office in France, is a worldwide hospitality company with more than 1000 hotels and 76,000 rooms in 50 countries. The Golden Tulip Hospitality Group franchises and manages hotels in Europe, Middle East & Africa, Asian Pacific Region and America with brands like Golden Tulip, Tulip Inn and Royal Tulip.</p>', ' 8 G.T Road, Model Town, Amritsar, Punjab- 143001.'),
(208, 'RADISSON BLU  HOTEL', 3, 'Rs.4500', '<h2>Radisson Blu</2>\r\n	<p style=\"text-align:justify\">Ideally situated near the International and Domestic Airport, the Radisson Blu Hotel Amritsar offers a seamless unison of modern design and upscale interiors, surrounded by lush green fields offering a relaxing environment perfect for business and leisure guests. The hotel’s 186 chic and spacious rooms and suites offer complimentary broadband Internet access, flat-screen LCD TVs and fully stocked mini bars. The Radisson Blu also features on-site dining, stylish lounge bar, full-service spa, outdoor pool, Fitness Centre and dedicated travel desk.</p>', '  Airport Road, Amritsar 143001 Punjab'),
(209, 'THE IMPERIAL HOTEL', 3, 'Rs.5500', '<h2>The Imperial</h2>\r\n	<p style=\"text-align:justify\">Reckoned amongst Asia’s finest hotels, The Imperial is a legend that offers a unique experience embracing facets of India’s history. Conceptualized in 1934 by Blomfield and inaugurated by Lord Wiilingdon in 1936, it was in Lutyens scheme of things to build the most luxurious hotel in New Delhi. As New Delhi’s landmark Hotel, it is located on anpath, the erstwhile Queensway. It is steps away from the renowned shopping district and major city attractions and a half-hour drive from the international airport. The hotel is a glorious, successful mixture of Victorian, Indian Colonial and Thirties Deco. The marble inlay work in floors, in both public and private rooms, displays the tradition of craftsmanship handed down since the Mughals brought their skills to the Taj Mahal. The hotel offers all the modern facilities with excellent service.</p>\r\n	<h5>Stays Includes </h5>\r\n		<p style=\"text-align:justify\">Two Bottles of Mineral Water, Daily National Newspaper, Fresh Fruit Platter, Shoe shine facility on request, Dental kit on request, Shaving kit on request.</p>', 'anpath Lane, Connaught Place, New Delhi, 110001 India'),
(210, 'GOLDEN TULIP HOTEL', 2, 'Rs.3500', '<h2>Golden Tulip</h2>\r\n	<p style=\"text-align:justify\">The Golden Tulip Jaipur is a deluxe, contemporary hotel, located in the heart of Jaipur. Over the years Golden Tulip has defined a benchmark of fine living and has expressed high standards in the art of hospitality worldwide. Golden Tulip, Jaipur is a blend of International standards and local flavors and it has retained the spirit and charm of the traditions of India and has blended these with the latest technology that the industry has to offer. For more than four decades, Golden Tulip Hotels, Inns & Resorts is having the continued honor of serving many distinguished guests who have their appreciation of the high standards of hospitality and service. All 108 rooms are well appointed, quite spacious and tastefully developed in modern setting. A Hotel which is indeed classy as well as contemporary suited both for leisure and business travelers.</p>', '  Nirwan Marg, Jaipur'),
(211, 'SUN AND SAND HOTEL', 3, 'Rs.5500', '<h2>Sun and Sand</h2>\r\n<p style=\"text-align:justify\">Sun-n-Sand is a leading group of five star hotels which strives to serve both business and leisure travelers. The Mumbai property is the flagship hotel of the Sun-n-Sand group and was commissioned in 1962.</p>	<p style=\"text-align:justify\">It was the vision of Mr. R. J. Advani and Mr. Jack Voyantzis which gave birth to Mumbai’s first five star beach hotel. Five decades of operations and constant innovations since then have assisted Sun-n- Sand to understand and master the art of serving guests. Since 1996, under the leadership of Mr. Rajesh Advani (Managing Director) the Sun-n-Sand group has leveraged its presence at strategic business and leisure destinations in Maharashtra. The group, besides, Mumbai, currently operates 5 star hotels at Pune, Shirdi and Nagpur.</p><p style=\"text-align:justify\"> The latest addition to the hotel chain (Sun-n-Sand Nagpur) was opened in the end of 2009 making Sun-n-Sand Hotels one of the largest regional five star hotel chains in Maharashtra.</p><p style=\"text-align:justify\">\r\n	All hotels have been planned and built keeping in mind the convenience of both business as well as leisure travelers. All our properties are located close to the airport. Besides this, a wide range of facilities and amenities have been introduced to make the guests feel at home. </p>', ' Sun-n-Sand Mumbai 39, Juhu Beach Mumbai - 400 049 India\r\n'),
(212, 'HERITAGE INN  HOTEL', 1, 'Rs.3500', '<h2>Heritage Inn</h2>\r\n	<p style=\"text-align:justify\">The Comfort Inn Heritage is ideally located facing the famous Gloria Church. This Mumbai hotel is also near uhu Beach, Mumbai Zoo (eejamata Udyan), Nehru Planetarium and Elephanta Caves. The University of Mumbai is just minutes away.</p><p style=\"text-align:justify\">The hotel is close to major Mumbai railway stations, allowing for easy access to everything the city has to offer. Mumbai is the bustling, commercial capital of India and home to some of the countrys most important banking and financial institutions, industrial houses and large corporate headquarters. In addition, Mumbai is a major port with years of maritime history, and many well developed shipping-related businesses are based here.</p><p style=\"text-align:justify\"> Shopping in Mumbai is a memorable experience as you wander through the many outdoor markets and bazaars, featuring a broad collection of antiques, jewelry, leather goods, and handmade arts and crafts. Phoenix Mills is a huge shopping and entertainment complex, featuring dozens of stores, popular night clubs, and a variety of restaurants and bars. Be sure to visit the Majestic Coffee Shop, Nizams Heritage restaurant and Deccan Bar, all located on hotel premises</p>', 'Sant Savta marg, Opp. Gloria Church, Byculla,Mumbai - 400 027.INDIA'),
(213, 'THE PRIDE HOTEL ', 1, 'Rs.2500', '<h2>The Pride</h2>	\r\n	<p style=\"text-align:justify\">Pride Plaza Hotel, Chennai is counted among the most incredible 3 Star hotel proving supreme facilities like a Gymnasium, Spa and Jacuzzi and over the top services to all its guests. Located at a prime location in Chennai, Pride Plaza stands out to be one of best budget hotels. Along with that it offers best deals and offers for Meeting rooms, conference cum business center. Its signature restaurant  ‘ Puran-Da-Dhaba’ serving authentic Punjabi cuisine delights the guests with the charm of North India in city of South India.</p>', '216 E V R Periyar Salai, Poonamallee High Road, Kilpauk, Chennai – 600 010'),
(214, 'PARK PLAZA OMR HOTEL', 2, 'Rs.3500', '<h2>Park Plaza OMR</h2>\r\n	<p style=\"text-align:justify\">Park Plaza Chennai OMR is ideally located on Old Mahabalipuram Road, also known as the IT Corridor, providing business and leisure travellers with easy access to area offices, art galleries, theatres, restaurants and beaches. Travel just eight kilometres to sunbathe on the sandy shores of Elliot\'s Beach or 10 kilometres to browse the stores at Phoenix Mall. The hotel is also just 14 kilometres from Chennai International Airport (MAA) and offers a luxury car service for stress-free airport transfers. During your stay, recharge in the outdoor swimming pool, work out in the fitness centre or dine at Oasis, our 24- hour coffee shop. Before retreating to your comfortable room or suite, stop by our Winchester bar for a nightcap. Come morning, we can send you off for a day of sightseeing or meetings fortified with our complimentary hot breakfast.</p>\r\n	<h5>Stays Includes</h5>\r\n	<p style=\"text-align:justify\">Complimentary newspaper, Coat hanger stand, Shaving mirror, Shower cubicle, Complimentary, connental breakfast</p>', ' 142 Rajiv Gandhi Salai, Old Mahabalipuram Road, Thoraipakkam, Chennai 600097 India\r\n'),
(215, 'THE MARK HOTEL ', 1, 'Rs.2500', '<h2>The Mark </h2>\r\n	<p style=\"text-align:justify\">Welcome to the most unique 40 Rooms and Suits Budget Hotel at Kolkata. Which gives you the taste of our finest hospitality and personalized service. An Ideal place to where you can access all business hubs and leisure interests.</p>\r\n	<p style=\"text-align:justify\"> Conveniently Located at the heart of the city. 20 kms away from Netaji Subhas Chandra Bose Airport, 5kms away from Howrah Railway Station, 3kms away from Sealdah Railway Station, a kilo meter away from all main Places of Interest, New Market, all major Shopping Malls and Park Street Tube Railway Station.</p>  ', ' 31/2-A,Marquis Street, Kolkata,West Bengal 700016\r\n'),
(216, 'HOTEL HINDUSTHAN INTERNATIONAL', 2, 'Rs.2500', '<h2>Hotel Hindusthan International</h2>\r\n	<p style=\"text-align:justify\">HHI, one of the leading business hotels in Kolkata have an overhauled new look, a premium facia and a new-look lobby, welcoming you into this Kolkata hotel.</p><p style=\"text-align:justify\"> At every turn you discover a new face of your well-versed Kolkata hotel. From the well-groomed staff to the friendly new outlets like the health-club or the swimming pool, everything throws a vibe of warmth around and reflects a sense of trendy living that enchants guests from world over. This luxurious hotel located near Park Street, Kolkata, India, offers more than just good lodging. No wonder it is the preferred choice for fairy-tale weddings as much as for corporate power-talks.</p>', ' 235/1, AJC Bose Road, Kolkata\r\n'),
(217, 'MERADEN GRAND HOTEL', 1, 'Rs.2500', '<h2>Meraden Grand</h2>\r\n	<p style=\"text-align:justify\">Away from the city noise and still close, the is a 0.5 Km drive from the Railway station and 20 Km from the airport. Tourist places, shopping areas and ghats all in close proximity. A Grand Hotel with a perfect blend of contemporary international standards and time honored tradition, offers a complete range of dining and entertainment facilities. The Hotel is an infusion of tranquility, pampering and a myriad of leisure pursuits at the doorstep of the holy city of Varanasi. Elegant accommodation and satisfying amenities combined with his service create an engaging atmosphere that provides a welcome oasis for business and leisure travelers.</p>', '57 Patel Nagar, Cantonment Varanasi, 221002\r\n'),
(218, 'RADISSON HOTEL', 3, 'Rs.3500', '<h2>Radisson Hotel</h2>\r\n	<p style=\"text-align:justify\">Radisson Hotel Varanasi is a five-star hotel conveniently located in the heart of the city\'s main business district. The hotel\'s modern architecture, warm hospitality and top-notch services are sure to please business and leisure travelers. The Radisson features spacious, comfortable rooms and suites, an on-site spa, multiple dining outlets and well-equipped meeting facilities - a wealth of services not found at all Varanasi hotels.</p>', 'The Mall Cantonment, Mall Rd, Cantonment Rd, Varanasi Cantt, Varanasi, Uttar Pradesh');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `hotels`
--
ALTER TABLE `hotels`
  ADD PRIMARY KEY (`h_id`),
  ADD KEY `Type_ID` (`Type_ID`);

--
-- Constraints for dumped tables
--

--
-- Constraints for table `hotels`
--
ALTER TABLE `hotels`
  ADD CONSTRAINT `hotels_ibfk_1` FOREIGN KEY (`Type_ID`) REFERENCES `hotel_type_details` (`Type_ID`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
